let tracksData = [
  {
    title: "Saint Levant - WAZIRA",
    tempo: 123.05,
    energy: 0.174,
    danceability: 1.55,
    key: 0,
    valence: 23.33,
    acousticness: 0.63,
    camelot: "5A",
    audio: "sounds/wazira.mp3",
    popularity: 64,
  },
  {
    title: "Ludovico Einaudi - Nuvole Bianche",
    tempo: 117.45,
    energy: 0.029,
    danceability: 0.44,
    key: 8,
    valence: 25.41,
    acousticness: 0.85,
    camelot: "4B",
    audio: "sounds/nuvole_bianche.mp3",
    popularity: 74,
  },
  {
    title: "ROSALÍA - DESPECHÁ",
    tempo: 129.2,
    energy: 0.196,
    danceability: 2.06,
    key: 9,
    valence: 24.27,
    acousticness: 0.65,
    camelot: "8A",
    audio: "sounds/despecha.mp3",
    popularity: 75,
  },
  {
    title: "Malemolência",
    tempo: 143.55,
    energy: 0.12,
    danceability: 1.64,
    key: 7,
    valence: 25.48,
    acousticness: 0.68,
    camelot: "6A",
    audio: "sounds/malemolencia.mp3",
    popularity: 54,
  },
  {
    title: "LIBERTAD",
    tempo: 123.05,
    energy: 0.247,
    danceability: 1.82,
    key: 11,
    valence: 24.63,
    acousticness: 0.7,
    camelot: "4A",
    audio: "sounds/libertad.mp3",
    popularity: 0,
  },
  {
    title: "KEFFRAN - LIGNE 17",
    tempo: 172.27,
    energy: 0.119,
    danceability: 1.57,
    key: 4,
    valence: 24.02,
    acousticness: 0.72,
    camelot: "9A",
    audio: "sounds/ligne_17.mp3",
    popularity: 3,
  },
  {
    title: "Tribunal",
    tempo: 99.38,
    energy: 0.235,
    danceability: 2.06,
    key: 9,
    valence: 23.62,
    acousticness: 0.65,
    camelot: "7A",
    audio: "sounds/tribunal.mp3",
    popularity: 34,
  },
  {
    title: "Mae - seule",
    tempo: 143.55,
    energy: 0.168,
    danceability: 1.31,
    key: 6,
    valence: 23.82,
    acousticness: 0.7,
    camelot: "10A",
    audio: "sounds/mae_seule.mp3",
    popularity: 15,
  },
  {
    title: "À en mourir",
    tempo: 143.55,
    energy: 0.145,
    danceability: 0.62,
    key: 5,
    valence: 26.43,
    acousticness: 0.84,
    camelot: "7B",
    audio: "sounds/a_en_mourir.mp3",
    popularity: 5,
  },
  {
    title: "Amra - Transistor",
    tempo: 129.2,
    energy: 0.258,
    danceability: 1.75,
    key: 4,
    valence: 23.64,
    acousticness: 0.66,
    camelot: "9A",
    audio: "sounds/transistor.mp3",
    popularity: 1,
  },
  {
    title: "Tus Besos - Eliah",
    tempo: 117.45,
    energy: 0.222,
    danceability: 1.67,
    key: 8,
    valence: 23.77,
    acousticness: 0.69,
    camelot: "4A",
    audio: "sounds/tus_besos.mp3",
    popularity: 1,
  },
  {
    title: "Oslow - Laurent De La House",
    tempo: 123.05,
    energy: 0.188,
    danceability: 1.55,
    key: 8,
    valence: 23.64,
    acousticness: 0.64,
    camelot: "4B",
    audio: "sounds/laurent_de_la_house.mp3",
    popularity: 13,
  },
  {
    title: "coti et canettes",
    tempo: 184.57,
    energy: 0.242,
    danceability: 2.26,
    key: 0,
    valence: 23.02,
    acousticness: 0.68,
    camelot: "8B",
    audio: "sounds/coti_et_canettes.mp3",
    popularity: 24,
  },
  {
    title: "Infina",
    tempo: 129.2,
    energy: 0.206,
    danceability: 2.04,
    key: 4,
    valence: 21.85,
    acousticness: 0.81,
    camelot: "9A",
    audio: "sounds/infina.mp3",
    popularity: 4,
  },
  {
    title: "Timide (feat. Obé)",
    tempo: 107.67,
    energy: 0.154,
    danceability: 1.46,
    key: 2,
    valence: 23.58,
    acousticness: 0.78,
    camelot: "7A",
    audio: "sounds/timide.mp3",
    popularity: 9,
  },
  {
    title: "Si simple...",
    tempo: 117.45,
    energy: 0.126,
    danceability: 1.64,
    key: 3,
    valence: 25.59,
    acousticness: 0.74,
    camelot: "1B",
    audio: "sounds/si_simple.mp3",
    popularity: 4,
  },
  {
    title: "STAY",
    tempo: 107.67,
    energy: 0.15,
    danceability: 1.29,
    key: 0,
    valence: 24.16,
    acousticness: 0.74,
    camelot: "8B",
    audio: "sounds/stay.mp3",
    popularity: 18,
  },
  {
    title: "Merci (fantômes de mon cœur)",
    tempo: 152.0,
    energy: 0.336,
    danceability: 1.15,
    key: 6,
    valence: 22.66,
    acousticness: 0.57,
    camelot: "12B",
    audio: "sounds/merci.mp3",
    popularity: 0,
  },
  {
    title: "Divergency - Mask",
    tempo: 103.36,
    energy: 0.245,
    danceability: 1.11,
    key: 7,
    valence: 23.8,
    acousticness: 0.66,
    camelot: "5A",
    audio: "sounds/mask.mp3",
    popularity: 0,
  },
  {
    title: "Moms - BACKTOBACK (Freestyle)",
    tempo: 69.84,
    energy: 0.139,
    danceability: 1.59,
    key: 2,
    valence: 23.23,
    acousticness: 0.5,
    camelot: "7A",
    audio: "sounds/backtoback.mp3",
    popularity: 3,
  },
  {
    title: "GAMINS (feat. Caramilk)",
    tempo: 112.35,
    energy: 0.229,
    danceability: 1.54,
    key: 0,
    valence: 21.47,
    acousticness: 0.6,
    camelot: "5A",
    audio: "sounds/gamins.mp3",
    popularity: 0,
  },
  {
    title: "Bleu (acoustique) - Kay Yōko x DIVIN3",
    tempo: 92.29,
    energy: 0.121,
    danceability: 0.87,
    key: 11,
    valence: 27.18,
    acousticness: 0.78,
    camelot: "9A",
    audio: "sounds/bleu_acoustique.mp3",
    popularity: 2,
  },
  {
    title: "Daej Phantom ft. Makala - Ratchet Paradise",
    tempo: 161.5,
    energy: 0.326,
    danceability: 2.26,
    key: 5,
    valence: 21.85,
    acousticness: 0.63,
    camelot: "4A",
    audio: "sounds/ratchet_paradise.mp3",
    popularity: 24,
  },
  {
    title: "DeWolph - ROOF",
    tempo: 136.0,
    energy: 0.166,
    danceability: 2.1,
    key: 6,
    valence: 22.81,
    acousticness: 0.64,
    camelot: "11A",
    audio: "sounds/roof.mp3",
    popularity: 0,
  },
  {
    title: "VOICE OF RUIN - Bloody Salvation",
    tempo: 123.05,
    energy: 0.218,
    danceability: 1.06,
    key: 8,
    valence: 22.62,
    acousticness: 0.55,
    camelot: "12A",
    audio: "sounds/bloody_salvation.mp3",
    popularity: 13,
  },
  {
    title: "Zuludog - Sideline",
    tempo: 95.7,
    energy: 0.11,
    danceability: 1.21,
    key: 2,
    valence: 24.88,
    acousticness: 0.73,
    camelot: "10A",
    audio: "sounds/sideline.mp3",
    popularity: 0,
  },
  {
    title: "Olympic Antigua - So Long",
    tempo: 86.13,
    energy: 0.267,
    danceability: 1.28,
    key: 11,
    valence: 23.64,
    acousticness: 0.62,
    camelot: "10A",
    audio: "sounds/so_long.mp3",
    popularity: 15,
  },
];
let maps = [];
let chunkSize = 20; // nombre de morceaux par map
let scoreThreshold = 0;

for (let i = 0; i < tracksData.length; i += chunkSize) {
  let chunk = tracksData.slice(i, i + chunkSize);
  maps.push({
    name: "Map " + (maps.length + 1),
    unlockScore: scoreThreshold,
    tracks: chunk,
  });
  scoreThreshold += 20; // chaque map est débloquée tous les 20 points
}
